#!/home/users/chenguang02/.jumbo/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'httpie==1.0.0.dev0','console_scripts','http'
__requires__ = 'httpie==1.0.0.dev0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('httpie==1.0.0.dev0', 'console_scripts', 'http')()
    )
